### ISSUE TITLE
Sorting problem when applied to Image

### ISSUE THREAD

**Issue by fugogugo** [greggman/hsva-unity#2]
Hi again!

so I just tried this shader into my project, and I applied it into Unity UI Image material.

and this shader causing layer sorting problem on the UI, which is when I add some  semi transparent image overlay on top of the image using the material, the image won't get overlaid and just stay on top of the overlay.

how should I fix this?

**Comment by rokolczuk** [comment]
I have the same issue.. It just doesn't get sorted with sprites rendered with default sprite material.

**Comment by greggman** [comment]
Uploaded a new version. See if it works for you
